/**
 * cQikly — Theme Definitions
 * Built in: Phase 1a-ii-A (CSS variable system)
 * Visual assets (Three.js scenes, animations) implemented in Phase 3b-ii.
 *
 * Each theme is a set of CSS custom property values applied to :root.
 * ThemeContext swaps these instantly at runtime — zero flicker, zero reload.
 *
 * 6 themes × 2 variants = 12 total CSS variable sets.
 * Hard Spec #27.
 */

export type ThemeId =
  | 'space-particles'
  | 'sakura'
  | 'minimal'
  | 'dark-rainbow'
  | 'neon'
  | 'dark-rose'

export type ThemeVariant = 'dark' | 'light'

/** A complete set of CSS custom property values for one theme variant */
export type ThemeCSSVars = Record<string, string>

export const THEME_META: Record<ThemeId, { label: string; hasAnimation: boolean }> = {
  'space-particles': { label: 'Space Particles', hasAnimation: true },
  'sakura':          { label: 'Sakura Flowers',  hasAnimation: true },
  'minimal':         { label: 'Minimal',         hasAnimation: false },
  'dark-rainbow':    { label: 'Dark Rainbow',    hasAnimation: true },
  'neon':            { label: 'Neon',            hasAnimation: true },
  'dark-rose':       { label: 'Dark Rose',       hasAnimation: true },
}

export const ALL_THEME_IDS: ThemeId[] = [
  'space-particles',
  'sakura',
  'minimal',
  'dark-rainbow',
  'neon',
  'dark-rose',
]

// ─── CSS Variable Sets ────────────────────────────────────────────────────────
// These tokens drive every colour decision in the app.
// shadcn/ui tokens (background, foreground, card, primary…) +
// cQikly-specific tokens (--cq-accent, --cq-glow, --cq-surface, --cq-bg-anim…).
//
// --cq-bg-primary   : main background colour
// --cq-bg-secondary : subtle secondary surface
// --cq-accent       : brand / highlight colour
// --cq-accent-light : lighter variant of accent
// --cq-glow         : glow / shadow colour (for neon-style effects)
// --cq-text-primary : primary text
// --cq-text-muted   : secondary / muted text
// --cq-border       : border colour
// --cq-surface      : card / raised surface
// --cq-surface-raised: modal / top-level surface
// --cq-anim-enabled : "1" | "0"  — set by ThemeContext from perf mode

type ThemePack = { dark: ThemeCSSVars; light: ThemeCSSVars }

export const THEME_CSS_VARS: Record<ThemeId, ThemePack> = {

  // ── 1. Space Particles (default) ──────────────────────────────────────────
  'space-particles': {
    dark: {
      '--background':           '224 47% 5%',
      '--foreground':           '210 40% 94%',
      '--card':                 '224 47% 8%',
      '--card-foreground':      '210 40% 94%',
      '--popover':              '224 47% 8%',
      '--popover-foreground':   '210 40% 94%',
      '--primary':              '217 91% 60%',
      '--primary-foreground':   '224 47% 5%',
      '--secondary':            '217 32% 17%',
      '--secondary-foreground': '210 40% 94%',
      '--muted':                '217 32% 13%',
      '--muted-foreground':     '215 20% 55%',
      '--accent':               '217 32% 17%',
      '--accent-foreground':    '210 40% 94%',
      '--destructive':          '0 84% 60%',
      '--destructive-foreground':'210 40% 98%',
      '--border':               '217 32% 15%',
      '--input':                '217 32% 15%',
      '--ring':                 '217 91% 60%',
      '--cq-bg-primary':        '#050b18',
      '--cq-bg-secondary':      '#0d1829',
      '--cq-accent':            '#3b82f6',
      '--cq-accent-light':      '#93c5fd',
      '--cq-glow':              '#3b82f6',
      '--cq-text-primary':      '#e2e8f0',
      '--cq-text-muted':        '#64748b',
      '--cq-border':            '#1e3a5f',
      '--cq-surface':           '#0d1829',
      '--cq-surface-raised':    '#162035',
    },
    light: {
      '--background':           '210 40% 98%',
      '--foreground':           '224 47% 8%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '224 47% 8%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '224 47% 8%',
      '--primary':              '217 91% 50%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '210 40% 92%',
      '--secondary-foreground': '224 47% 8%',
      '--muted':                '210 40% 94%',
      '--muted-foreground':     '215 20% 45%',
      '--accent':               '210 40% 92%',
      '--accent-foreground':    '224 47% 8%',
      '--destructive':          '0 84% 55%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '214 32% 86%',
      '--input':                '214 32% 86%',
      '--ring':                 '217 91% 50%',
      '--cq-bg-primary':        '#f0f6ff',
      '--cq-bg-secondary':      '#e0ecff',
      '--cq-accent':            '#2563eb',
      '--cq-accent-light':      '#1d4ed8',
      '--cq-glow':              '#3b82f6',
      '--cq-text-primary':      '#1e3a5f',
      '--cq-text-muted':        '#64748b',
      '--cq-border':            '#bfdbfe',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#f8faff',
    },
  },

  // ── 2. Sakura ─────────────────────────────────────────────────────────────
  sakura: {
    dark: {
      '--background':           '340 25% 8%',
      '--foreground':           '340 30% 93%',
      '--card':                 '340 25% 11%',
      '--card-foreground':      '340 30% 93%',
      '--popover':              '340 25% 11%',
      '--popover-foreground':   '340 30% 93%',
      '--primary':              '340 72% 65%',
      '--primary-foreground':   '340 25% 8%',
      '--secondary':            '340 20% 20%',
      '--secondary-foreground': '340 30% 93%',
      '--muted':                '340 15% 16%',
      '--muted-foreground':     '340 12% 55%',
      '--accent':               '340 20% 20%',
      '--accent-foreground':    '340 30% 93%',
      '--destructive':          '0 84% 60%',
      '--destructive-foreground':'0 0% 98%',
      '--border':               '340 18% 20%',
      '--input':                '340 18% 20%',
      '--ring':                 '340 72% 65%',
      '--cq-bg-primary':        '#180c12',
      '--cq-bg-secondary':      '#241019',
      '--cq-accent':            '#e8698a',
      '--cq-accent-light':      '#f4a7bb',
      '--cq-glow':              '#e8698a',
      '--cq-text-primary':      '#f5dde5',
      '--cq-text-muted':        '#9a6b7a',
      '--cq-border':            '#4a1e2e',
      '--cq-surface':           '#241019',
      '--cq-surface-raised':    '#2e1420',
    },
    light: {
      '--background':           '340 60% 98%',
      '--foreground':           '340 25% 15%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '340 25% 15%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '340 25% 15%',
      '--primary':              '340 72% 55%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '340 40% 92%',
      '--secondary-foreground': '340 25% 15%',
      '--muted':                '340 40% 94%',
      '--muted-foreground':     '340 20% 50%',
      '--accent':               '340 40% 92%',
      '--accent-foreground':    '340 25% 15%',
      '--destructive':          '0 84% 55%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '340 40% 86%',
      '--input':                '340 40% 86%',
      '--ring':                 '340 72% 55%',
      '--cq-bg-primary':        '#fff5f8',
      '--cq-bg-secondary':      '#ffe4ec',
      '--cq-accent':            '#d63864',
      '--cq-accent-light':      '#b91c4a',
      '--cq-glow':              '#e8698a',
      '--cq-text-primary':      '#3d0e1e',
      '--cq-text-muted':        '#9a6b7a',
      '--cq-border':            '#f9c0d0',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#fff9fb',
    },
  },

  // ── 3. Minimal ────────────────────────────────────────────────────────────
  minimal: {
    dark: {
      '--background':           '0 0% 7%',
      '--foreground':           '0 0% 92%',
      '--card':                 '0 0% 10%',
      '--card-foreground':      '0 0% 92%',
      '--popover':              '0 0% 10%',
      '--popover-foreground':   '0 0% 92%',
      '--primary':              '0 0% 80%',
      '--primary-foreground':   '0 0% 7%',
      '--secondary':            '0 0% 16%',
      '--secondary-foreground': '0 0% 92%',
      '--muted':                '0 0% 13%',
      '--muted-foreground':     '0 0% 48%',
      '--accent':               '0 0% 16%',
      '--accent-foreground':    '0 0% 92%',
      '--destructive':          '0 70% 55%',
      '--destructive-foreground':'0 0% 98%',
      '--border':               '0 0% 18%',
      '--input':                '0 0% 18%',
      '--ring':                 '0 0% 70%',
      '--cq-bg-primary':        '#121212',
      '--cq-bg-secondary':      '#1a1a1a',
      '--cq-accent':            '#d4d4d4',
      '--cq-accent-light':      '#a3a3a3',
      '--cq-glow':              '#737373',
      '--cq-text-primary':      '#ededed',
      '--cq-text-muted':        '#737373',
      '--cq-border':            '#2e2e2e',
      '--cq-surface':           '#1a1a1a',
      '--cq-surface-raised':    '#222222',
    },
    light: {
      '--background':           '0 0% 99%',
      '--foreground':           '0 0% 9%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '0 0% 9%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '0 0% 9%',
      '--primary':              '0 0% 15%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '0 0% 92%',
      '--secondary-foreground': '0 0% 9%',
      '--muted':                '0 0% 95%',
      '--muted-foreground':     '0 0% 50%',
      '--accent':               '0 0% 92%',
      '--accent-foreground':    '0 0% 9%',
      '--destructive':          '0 70% 50%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '0 0% 88%',
      '--input':                '0 0% 88%',
      '--ring':                 '0 0% 25%',
      '--cq-bg-primary':        '#fafafa',
      '--cq-bg-secondary':      '#f0f0f0',
      '--cq-accent':            '#1a1a1a',
      '--cq-accent-light':      '#404040',
      '--cq-glow':              '#737373',
      '--cq-text-primary':      '#171717',
      '--cq-text-muted':        '#737373',
      '--cq-border':            '#e5e5e5',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#f9f9f9',
    },
  },

  // ── 4. Dark Rainbow ───────────────────────────────────────────────────────
  'dark-rainbow': {
    dark: {
      '--background':           '260 30% 6%',
      '--foreground':           '0 0% 95%',
      '--card':                 '260 28% 9%',
      '--card-foreground':      '0 0% 95%',
      '--popover':              '260 28% 9%',
      '--popover-foreground':   '0 0% 95%',
      '--primary':              '280 80% 65%',
      '--primary-foreground':   '260 30% 6%',
      '--secondary':            '260 25% 18%',
      '--secondary-foreground': '0 0% 95%',
      '--muted':                '260 22% 13%',
      '--muted-foreground':     '260 15% 55%',
      '--accent':               '260 25% 18%',
      '--accent-foreground':    '0 0% 95%',
      '--destructive':          '0 84% 60%',
      '--destructive-foreground':'0 0% 98%',
      '--border':               '260 22% 18%',
      '--input':                '260 22% 18%',
      '--ring':                 '280 80% 65%',
      '--cq-bg-primary':        '#0a0710',
      '--cq-bg-secondary':      '#130e1c',
      '--cq-accent':            '#a855f7',   // starts purple; JS animation cycles hue
      '--cq-accent-light':      '#d8b4fe',
      '--cq-glow':              '#a855f7',
      '--cq-text-primary':      '#f3f4f6',
      '--cq-text-muted':        '#6b7280',
      '--cq-border':            '#2e1f4a',
      '--cq-surface':           '#130e1c',
      '--cq-surface-raised':    '#1a1228',
    },
    light: {
      '--background':           '260 60% 97%',
      '--foreground':           '260 30% 10%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '260 30% 10%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '260 30% 10%',
      '--primary':              '280 80% 55%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '260 40% 92%',
      '--secondary-foreground': '260 30% 10%',
      '--muted':                '260 40% 94%',
      '--muted-foreground':     '260 20% 50%',
      '--accent':               '260 40% 92%',
      '--accent-foreground':    '260 30% 10%',
      '--destructive':          '0 84% 55%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '260 40% 86%',
      '--input':                '260 40% 86%',
      '--ring':                 '280 80% 55%',
      '--cq-bg-primary':        '#f9f5ff',
      '--cq-bg-secondary':      '#ede9fe',
      '--cq-accent':            '#7c3aed',
      '--cq-accent-light':      '#6d28d9',
      '--cq-glow':              '#a855f7',
      '--cq-text-primary':      '#1e1040',
      '--cq-text-muted':        '#6b7280',
      '--cq-border':            '#ddd6fe',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#faf5ff',
    },
  },

  // ── 5. Neon ───────────────────────────────────────────────────────────────
  neon: {
    dark: {
      '--background':           '220 40% 4%',
      '--foreground':           '180 100% 90%',
      '--card':                 '220 40% 7%',
      '--card-foreground':      '180 100% 90%',
      '--popover':              '220 40% 7%',
      '--popover-foreground':   '180 100% 90%',
      '--primary':              '176 100% 50%',
      '--primary-foreground':   '220 40% 4%',
      '--secondary':            '220 30% 14%',
      '--secondary-foreground': '180 100% 85%',
      '--muted':                '220 28% 10%',
      '--muted-foreground':     '200 30% 55%',
      '--accent':               '296 100% 60%',
      '--accent-foreground':    '220 40% 4%',
      '--destructive':          '0 100% 55%',
      '--destructive-foreground':'0 0% 98%',
      '--border':               '220 30% 15%',
      '--input':                '220 30% 15%',
      '--ring':                 '176 100% 50%',
      '--cq-bg-primary':        '#030a0e',
      '--cq-bg-secondary':      '#060f16',
      '--cq-accent':            '#00f5d4',   // cyan
      '--cq-accent-light':      '#ff00ff',   // magenta
      '--cq-glow':              '#00f5d4',
      '--cq-text-primary':      '#e0fffc',
      '--cq-text-muted':        '#4a7a80',
      '--cq-border':            '#003344',
      '--cq-surface':           '#060f16',
      '--cq-surface-raised':    '#0b1a22',
    },
    light: {
      '--background':           '195 80% 96%',
      '--foreground':           '220 40% 8%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '220 40% 8%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '220 40% 8%',
      '--primary':              '176 90% 35%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '195 60% 90%',
      '--secondary-foreground': '220 40% 8%',
      '--muted':                '195 60% 93%',
      '--muted-foreground':     '200 30% 45%',
      '--accent':               '296 80% 50%',
      '--accent-foreground':    '0 0% 100%',
      '--destructive':          '0 84% 55%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '195 50% 84%',
      '--input':                '195 50% 84%',
      '--ring':                 '176 90% 35%',
      '--cq-bg-primary':        '#f0fffe',
      '--cq-bg-secondary':      '#d9f9f6',
      '--cq-accent':            '#009984',
      '--cq-accent-light':      '#7c00b5',
      '--cq-glow':              '#00c4a7',
      '--cq-text-primary':      '#0a2020',
      '--cq-text-muted':        '#4a7a80',
      '--cq-border':            '#a7e8e0',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#f5fffd',
    },
  },

  // ── 6. Dark Rose ──────────────────────────────────────────────────────────
  'dark-rose': {
    dark: {
      '--background':           '330 28% 6%',
      '--foreground':           '330 30% 93%',
      '--card':                 '330 26% 9%',
      '--card-foreground':      '330 30% 93%',
      '--popover':              '330 26% 9%',
      '--popover-foreground':   '330 30% 93%',
      '--primary':              '330 60% 60%',
      '--primary-foreground':   '330 28% 6%',
      '--secondary':            '330 20% 17%',
      '--secondary-foreground': '330 30% 93%',
      '--muted':                '330 16% 13%',
      '--muted-foreground':     '330 12% 52%',
      '--accent':               '300 35% 50%',
      '--accent-foreground':    '330 28% 6%',
      '--destructive':          '0 70% 55%',
      '--destructive-foreground':'0 0% 98%',
      '--border':               '330 18% 18%',
      '--input':                '330 18% 18%',
      '--ring':                 '330 60% 60%',
      '--cq-bg-primary':        '#0f0710',
      '--cq-bg-secondary':      '#180e18',
      '--cq-accent':            '#c4648a',   // rose
      '--cq-accent-light':      '#e8a7bf',   // dusty pink
      '--cq-glow':              '#c4648a',
      '--cq-text-primary':      '#f5e8ef',
      '--cq-text-muted':        '#8c6070',
      '--cq-border':            '#3d1a2a',
      '--cq-surface':           '#180e18',
      '--cq-surface-raised':    '#22122a',
    },
    light: {
      '--background':           '330 60% 98%',
      '--foreground':           '330 28% 12%',
      '--card':                 '0 0% 100%',
      '--card-foreground':      '330 28% 12%',
      '--popover':              '0 0% 100%',
      '--popover-foreground':   '330 28% 12%',
      '--primary':              '330 60% 50%',
      '--primary-foreground':   '0 0% 100%',
      '--secondary':            '330 40% 92%',
      '--secondary-foreground': '330 28% 12%',
      '--muted':                '330 40% 95%',
      '--muted-foreground':     '330 20% 50%',
      '--accent':               '300 35% 70%',
      '--accent-foreground':    '330 28% 12%',
      '--destructive':          '0 70% 50%',
      '--destructive-foreground':'0 0% 100%',
      '--border':               '330 40% 86%',
      '--input':                '330 40% 86%',
      '--ring':                 '330 60% 50%',
      '--cq-bg-primary':        '#fff5f8',
      '--cq-bg-secondary':      '#ffe0ea',
      '--cq-accent':            '#c4648a',
      '--cq-accent-light':      '#9c3a5e',
      '--cq-glow':              '#e8a7bf',
      '--cq-text-primary':      '#3d0a1c',
      '--cq-text-muted':        '#8c6070',
      '--cq-border':            '#f9c0d3',
      '--cq-surface':           '#ffffff',
      '--cq-surface-raised':    '#fff9fb',
    },
  },
}
